[package]
name = "isoflux"
version = "0.1.0-alpha.1"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Command-Query Responsibility Segregation (CQRS) and Event Sourcing (ES) framework for Rust"

[dependencies]
isoflux-core = { version = "0.1.0-alpha.1", path = "../core" }
